---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aws-example-octodex
  labels:
    app: aws-example-octodex
  annotations:
    fluxcd.io/automated: "true"
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  selector:
    matchLabels:
      app: aws-example-octodex
  template:
    metadata:
      labels:
        app: aws-example-octodex
    spec:
      containers:
      - name: aws-example-octodex
        image: 035131886610.dkr.ecr.us-east-2.amazonaws.com/example-eks:72a1b2c9e4c0e9952f91be6e2e092b2ea840d17f
        ports:
        - containerPort: 9000
        resources:
          requests:
            cpu: 250m
          limits:
            cpu: 500m
            memory: 1024m
